context_size: 60
patch_size: 16
image_size: 224
vocab_size: 5000

image_encoder:
  stack_size: 6
  num_heads: 8
  hidden_size: 512
  key_size: 64
  value_size: 64
  feedforward_size: 2048
  dropout: 0.1

image_decoder:
  stack_size: 4         
  num_heads: 8          
  hidden_size: 512      
  key_size: 64
  value_size: 64
  feedforward_size: 1024 
  dropout: 0.1

caption_decoder:
  stack_size: 6
  num_heads: 8
  hidden_size: 512
  key_size: 64
  value_size: 64
  feedforward_size: 2048
  dropout: 0.1

batch_size: 128
num_workers: 10 # Set according to your hardware
captioner_epochs: 1 # Number of additional (not total) of epochs.
image_encoder_epochs: 1

masking_ratio: 0.75