context_size: 60
patch_size: 16
image_size: 224
vocab_size: 5000

image_encoder:
  stack_size: 14
  num_heads: 12
  hidden_size: 768
  key_size: 64
  value_size: 64
  feedforward_size: 3072
  dropout: 0.1

image_decoder:
  stack_size: 4         
  num_heads: 8          
  hidden_size: 768     
  key_size: 64
  value_size: 64
  feedforward_size: 1024 
  dropout: 0.1

caption_decoder:
  stack_size: 6
  num_heads: 12
  hidden_size: 768
  key_size: 64
  value_size: 64
  feedforward_size: 3072
  dropout: 0.1

# Data loader
batch_size: 128
num_workers: 10 # Set according to your hardware

# Encoder training
total_image_encoder_epochs: 90
cur_image_encoder_epochs: 5 # The number of epochs for the next compute.
auto_encoder_warmup_epochs: 8
masking_ratio: 0.75
auto_encoder_lr: 8e-5
auto_encoder_start_factor: 0.05
auto_encoder_eta_min: 1e-6
auto_encoder_wd: 0.05

# Captioner training
total_captioner_epochs: 30
cur_captioner_epochs: 1
captioner_lr: 1e-4
auto_encoder_start_factor: 0.05
auto_encoder_eta_min: 1e-6
captioner_wd: 0.05
label_smoothing: 0.01
eval_freq: 1