context_size: 60
patch_size: 16
image_size: 224
vocab_size: 5000

transformer_encoder:
  stack_size: 6
  num_heads: 8
  hidden_size: 512
  key_size: 64
  value_size: 64
  feedforward_size: 2048
  dropout: 0.1

transformer_decoder:
  stack_size: 6
  num_heads: 8
  hidden_size: 512
  key_size: 64
  value_size: 64
  feedforward_size: 2048
  dropout: 0.1

batch_size: 128
num_workers: 10 # Set according to your hardware
epochs: 1 # Number of additional (not total) of epochs.